#%RAML 1.0
---
title: FSO Scheduler
mediaType: application/json
version: 1

types:
  Appointment: !include types/appointment.raml
  Assignment: !include types/assignment.raml
  Assignments: !include types/assignments.raml
  AppointmentIds: !include types/appointmentIds.raml
  RecommendationGet: !include types/recommendation-get.raml
  Recommendation: !include types/recommendation.raml

/appointments:
  post:
    description: Add a new appointment.
    body:
      type: Appointment
    responses:
      201:
        body:
          example: !include examples/post-appointment.json
      400:
        body:
          example: !include examples/error.json
  /assignment:
    post:
      description: Assign multi-couples of one engineer per appointment.
      body:
        type: Assignments
      responses:
        200:
          body:
            example: !include examples/assignment.json
    delete:
      description: Unassign enginners from several appointments
      body:
        type: AppointmentIds
      responses:
        204:
          body:


  /{id}/assignment:
    post:
      description: Assign an appointment to a engineer.
      body:
        type: Assignment
      responses:
        200:
          body:
            example: !include examples/single-assignment.json
        400:
          body:
            example: !include examples/error.json
    delete:
      description: Unassign a engineer from an appointment.
      body:

  /recommendations:
    post:
      description: Get recommendations of appointments.
      body:
        type: RecommendationGet
      responses:
        200:
          body:
            type: Recommendation
