#%RAML 1.0 DataType
type: object
properties:
  data:
    type: object
    properties:
      engineerId:
        type: string
        description: assigned engineer id
      assignedStart:
        required: false
        type: string
        description: assign event start time
      assignedEnd:
        required: false
        type: string
        description: assign event end time
      force:
        required: false
        type: boolean
        description: controller for skipping pre-check, force assign engineer

    description: assignment infomation
